"""Add affiliate functionality and update Order model

Revision ID: 8f20a4acc293
Revises: ab5d9d750fee
Create Date: 2025-06-16 14:21:56.843562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f20a4acc293'
down_revision = 'ab5d9d750fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliate', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('affiliate', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('affiliate_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('commission_earned', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'order', 'affiliate', ['affiliate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'commission_earned')
    op.drop_column('order', 'affiliate_id')
    op.drop_column('affiliate', 'created_at')
    op.drop_column('affiliate', 'is_active')
    # ### end Alembic commands ###
